
/* MACHINE GENERATED By Halide. */

#include <assert.h>
#include <float.h>
#include <limits.h>
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include <stdlib.h>

#ifndef HALIVER_GLOBALS
#define HALIVER_GLOBALS

struct halide_dimension_t {
    int32_t min, extent, stride;
};

inline void halide_unused(bool e){};

/*@
pure int max(int x, int y) = x > y ? x : y;

pure int min(int x, int y) = x > y ? y : x;

pure float max(float x, float y) = x > y ? x : y;

pure float min(float x, float y) = x > y ? y : x;

pure int abs(int x) = x >= 0 ? x : -x;

pure float abs(float x) = x >= 0 ? x : -x;

// Euclidean division is defined internally in VerCors
pure int hdiv(int x, int y) = y == 0 ? 0 : \euclidean_div(x, y);
pure int hmod(int x, int y) = y == 0 ? 0 : \euclidean_mod(x, y);
@*/

/*@
  requires y != 0;
  ensures \result == \euclidean_div(x, y);
@*/
inline int /*@ pure @*/ div_eucl(int x, int y)
{
    int q = x/y;
    int r = x%y;
    return r < 0 ? q + (y > 0 ? -1 : 1) : q;
}

/*@
  requires y != 0;
  ensures \result == \euclidean_mod(x, y);
@*/
inline int /*@ pure @*/ mod_eucl(int x, int y)
{
    int r = x%y;
    return (x >= 0 || r == 0) ? r : r + abs(y);
}

static inline int /*@ pure @*/ min(int x, int y) {return x < y ? x : y;}

static inline float /*@ pure @*/ fast_inverse_f32(float x) {return 1.0f/x;}
static inline float /*@ pure @*/ sqrt_f32(double x) {return (float)sqrt((double)x);}
static inline float /*@ pure @*/ pow_f32(float x, float y){ return (float) pow((double) x, (double) y);}
static inline float /*@ pure @*/ floor_f32(float x){ return (float) floor((double) x); }
static inline float /*@ pure @*/ ceil_f32(float x){ return (float) ceil((double) x); }
static inline float /*@ pure @*/ round_f32(float x){ return (float) round((double) x); }

static inline double /*@ pure @*/ sqrt_f64(double x) {return sqrt(x);}
static inline double /*@ pure @*/ pow_f64(double x, double y) {return pow(x, y);}
static inline double /*@ pure @*/ floor_f64(double x) {return floor(x);}
static inline double /*@ pure @*/ ceil_f64(double x) {return ceil(x);}
static inline double /*@ pure @*/ round_f64(double x){ return round(x); }

//inline float nan_f32() {return NAN;}
inline float nan_f32() {return 0.0f;}
/*@
inline resource dim_perm(struct halide_dimension_t *dim, rational p, int i) = 
 Perm(&dim[i], 1\2) **
 Perm(dim[i].min, 1\2) **
 Perm(dim[i].stride, 1\2) **
 Perm(dim[i].extent, 1\2)
 ;

 ghost
 requires a >= 0;
 requires b > 0;
 requires a < max_a;
 ensures a*b <= (max_a-1)*b;
 decreases b;
void lemma_nonlinear(int a, int b, int max_a)
;//{
//  if(b>1){
//    lemma_nonlinear(a, b-1, max_a);
//    assert a*(b-1) <= max_a*(b-1);
//  }
//}

 ghost
 requires a-min_a >= 0  && a-min_a<extent_a;
 requires b-min_b >= 0 && b-min_b<extent_b;
 requires stride_a > 0;
 requires stride_b > 0;
 requires stride_b >= extent_a*stride_a;

 ensures 0 <= (a-min_a)*stride_a + (b-min_b)*stride_b;
 ensures (a-min_a)*stride_a + (b-min_b)*stride_b < stride_b*extent_b;
 decreases;
void lemma_2d_access(
 int a, int min_a, int stride_a, int extent_a,
 int b, int min_b, int stride_b, int extent_b)
;//{
//  lemma_nonlinear(a-min_a, stride_a, extent_a);
//  lemma_nonlinear(b-min_b, stride_b, extent_b);
//  return;
//}

 ghost
 requires a-min_a >= 0 && a-min_a < extent_a;
 requires b-min_b >= 0 && b-min_b < extent_b;
 requires c-min_c >= 0 && c-min_c < extent_c;
 requires stride_a > 0;
 requires stride_b > 0;
 requires stride_c > 0;
 requires stride_b >= extent_a * stride_a;
 requires stride_c >= extent_b * stride_b;
 
 ensures 0 <= (a-min_a) * stride_a + (b-min_b) * stride_b + (c-min_c) * stride_c;
 ensures (a-min_a) * stride_a + (b-min_b) * stride_b + (c-min_c) * stride_c < stride_c * extent_c;
 decreases;
void lemma_3d_access(
  int a, int min_a, int stride_a, int extent_a,
  int b, int min_b, int stride_b, int extent_b,
  int c, int min_c, int stride_c, int extent_c
)
;//{
//  lemma_2d_access(a, min_a, stride_a, extent_a, b, min_b, stride_b, extent_b);
//  lemma_nonlinear(c-min_c, stride_c, extent_c);
//  return;
//}

 ghost
 requires a-min_a >= 0 && a-min_a < extent_a;
 requires b-min_b >= 0 && b-min_b < extent_b;
 requires c-min_c >= 0 && c-min_c < extent_c;
 requires d-min_d >= 0 && d-min_d < extent_d;
 requires stride_a > 0;
 requires stride_b > 0;
 requires stride_c > 0;
 requires stride_d > 0;
 requires stride_b >= extent_a * stride_a;
 requires stride_c >= extent_b * stride_b;
 requires stride_d >= extent_c * stride_c;

ensures 0 <= (a-min_a) * stride_a + (b-min_b) * stride_b + (c-min_c) * stride_c + (d-min_d) * stride_d;
ensures (a-min_a) * stride_a + (b-min_b) * stride_b + (c-min_c) * stride_c + (d-min_d) * stride_d < stride_d * extent_d;
decreases;
void lemma_4d_access(
  int a, int min_a, int stride_a, int extent_a,
  int b, int min_b, int stride_b, int extent_b,
  int c, int min_c, int stride_c, int extent_c,
  int d, int min_d, int stride_d, int extent_d
)
;//{
//  lemma_3d_access(a, min_a, stride_a, extent_a, b, min_b, stride_b, extent_b, c, min_c, stride_c, extent_c);
//  lemma_nonlinear(d-min_d, stride_d, extent_d);
//  return;
//}

 ghost
 requires a-min_a >= 0 && a-min_a < extent_a;
 requires b-min_b >= 0 && b-min_b < extent_b;
 requires c-min_c >= 0 && c-min_c < extent_c;
 requires d-min_d >= 0 && d-min_d < extent_d;
 requires e-min_e >= 0 && e-min_e < extent_e;
 requires stride_a > 0;
 requires stride_b > 0;
 requires stride_c > 0;
 requires stride_d > 0;
 requires stride_e > 0;
 requires stride_b >= extent_a * stride_a;
 requires stride_c >= extent_b * stride_b;
 requires stride_d >= extent_c * stride_c;
 requires stride_e >= extent_d * stride_d;
 
 ensures 0 <= (a-min_a) * stride_a + (b-min_b) * stride_b + (c-min_c) * stride_c + (d-min_d) * stride_d + (e-min_e) * stride_e;
 ensures (a-min_a) * stride_a + (b-min_b) * stride_b + (c-min_c) * stride_c + (d-min_d) * stride_d + (e-min_e) * stride_e < stride_e * extent_e;
 decreases;
void lemma_5d_access(
  int a, int min_a, int stride_a, int extent_a,
  int b, int min_b, int stride_b, int extent_b,
  int c, int min_c, int stride_c, int extent_c,
  int d, int min_d, int stride_d, int extent_d,
  int e, int min_e, int stride_e, int extent_e
)
;//{
//  lemma_4d_access(a, min_a, stride_a, extent_a, b, min_b, stride_b, extent_b, c, min_c, stride_c, extent_c, d, min_d, stride_d, extent_d);
//  lemma_nonlinear(e-min_e, stride_e, extent_e);
//  return;
//}
@*/
#endif // HALIVER_GLOBALS

#ifndef HALIDE_BUFFER_TYPE_DOUBLE
#define HALIDE_BUFFER_TYPE_DOUBLE
struct halide_buffer_double {

    /** The dimensionality of the buffer. */
    int32_t dimensions;

    /** The shape of the buffer. Halide does not own this array - you
     * must manage the memory for it yourself. */
    struct halide_dimension_t *dim;

    /** A pointer to the start of the data in main memory. In terms of
     * the Halide coordinate system, this is the address of the min
     * coordinates (defined below). */

    double *host;
};

/*@ 
 requires buf != NULL ** \pointer_length(buf) == 1 ** Perm(buf, 1\2);
 requires Perm(buf->host, 1\2);
 @*/
/*@ pure @*/ inline double *_halide_buffer_get_host_double(struct halide_buffer_double *buf) {
    return buf->host;
}

/*@ 
    requires buf != NULL ** \pointer_length(buf) == 1 ** Perm(buf, 1\2);
    requires Perm(buf->dim, 1\2) ** buf->dim != NULL;
    requires 0 <= d && d < \pointer_length(buf->dim);
    requires Perm(&buf->dim[d], 1\2);
    requires Perm(buf->dim[d].min, 1\2);
@*/
/*@ pure @*/ inline int _halide_buffer_get_min_double(struct halide_buffer_double *buf, int d) {
    return buf->dim[d].min;
}

/*@ 
    requires buf != NULL ** \pointer_length(buf) == 1 ** Perm(buf, 1\2);
    requires Perm(buf->dim, 1\2) ** buf->dim != NULL;
    requires 0 <= d && d < \pointer_length(buf->dim);
    requires Perm(&buf->dim[d], 1\2);
    requires Perm(buf->dim[d].min, 1\2) ** Perm(buf->dim[d].extent, 1\2);
@*/
/*@ pure @*/ inline int _halide_buffer_get_max_double(struct halide_buffer_double *buf, int d) {
    return buf->dim[d].min + buf->dim[d].extent - 1;
}

/*@ 
    requires buf != NULL ** \pointer_length(buf) == 1 ** Perm(buf, 1\2);
    requires Perm(buf->dim, 1\2) ** buf->dim != NULL;
    requires 0 <= d && d < \pointer_length(buf->dim);
    requires Perm(&buf->dim[d], 1\2);
    requires Perm(buf->dim[d].extent, 1\2);
@*/
/*@ pure @*/ inline int _halide_buffer_get_extent_double(struct halide_buffer_double *buf, int d) {
    return buf->dim[d].extent;
}

/*@ 
    requires buf != NULL ** \pointer_length(buf) == 1 ** Perm(buf, 1\2);
    requires Perm(buf->dim, 1\2) ** buf->dim != NULL;
    requires 0 <= d && d < \pointer_length(buf->dim);
    requires Perm(&buf->dim[d], 1\2);
    requires Perm(buf->dim[d].stride, 1\2);
@*/
/*@ pure @*/ inline int _halide_buffer_get_stride_double(struct halide_buffer_double *buf, int d) {
    return buf->dim[d].stride;
}

/*@
inline resource buffer_double(struct halide_buffer_double *buf, rational p, int n_dims) = 
 buf != NULL **
 \pointer_length(buf) == 1 **
 Perm(buf, p) **
 Perm(buf->dim, p) **
 buf->dim != NULL **
 \pointer_length(buf->dim) == n_dims **
 Perm(buf->host, p) **
 buf->host != NULL;
@*/
#endif //HALIDE_BUFFER_TYPE_DOUBLE
#ifndef HALIDE_BUFFER_TYPE_INT32_T
#define HALIDE_BUFFER_TYPE_INT32_T
struct halide_buffer_int32_t {

    /** The dimensionality of the buffer. */
    int32_t dimensions;

    /** The shape of the buffer. Halide does not own this array - you
     * must manage the memory for it yourself. */
    struct halide_dimension_t *dim;

    /** A pointer to the start of the data in main memory. In terms of
     * the Halide coordinate system, this is the address of the min
     * coordinates (defined below). */

    int32_t *host;
};

/*@ 
 requires buf != NULL ** \pointer_length(buf) == 1 ** Perm(buf, 1\2);
 requires Perm(buf->host, 1\2);
 @*/
/*@ pure @*/ inline int32_t *_halide_buffer_get_host_int32_t(struct halide_buffer_int32_t *buf) {
    return buf->host;
}

/*@ 
    requires buf != NULL ** \pointer_length(buf) == 1 ** Perm(buf, 1\2);
    requires Perm(buf->dim, 1\2) ** buf->dim != NULL;
    requires 0 <= d && d < \pointer_length(buf->dim);
    requires Perm(&buf->dim[d], 1\2);
    requires Perm(buf->dim[d].min, 1\2);
@*/
/*@ pure @*/ inline int _halide_buffer_get_min_int32_t(struct halide_buffer_int32_t *buf, int d) {
    return buf->dim[d].min;
}

/*@ 
    requires buf != NULL ** \pointer_length(buf) == 1 ** Perm(buf, 1\2);
    requires Perm(buf->dim, 1\2) ** buf->dim != NULL;
    requires 0 <= d && d < \pointer_length(buf->dim);
    requires Perm(&buf->dim[d], 1\2);
    requires Perm(buf->dim[d].min, 1\2) ** Perm(buf->dim[d].extent, 1\2);
@*/
/*@ pure @*/ inline int _halide_buffer_get_max_int32_t(struct halide_buffer_int32_t *buf, int d) {
    return buf->dim[d].min + buf->dim[d].extent - 1;
}

/*@ 
    requires buf != NULL ** \pointer_length(buf) == 1 ** Perm(buf, 1\2);
    requires Perm(buf->dim, 1\2) ** buf->dim != NULL;
    requires 0 <= d && d < \pointer_length(buf->dim);
    requires Perm(&buf->dim[d], 1\2);
    requires Perm(buf->dim[d].extent, 1\2);
@*/
/*@ pure @*/ inline int _halide_buffer_get_extent_int32_t(struct halide_buffer_int32_t *buf, int d) {
    return buf->dim[d].extent;
}

/*@ 
    requires buf != NULL ** \pointer_length(buf) == 1 ** Perm(buf, 1\2);
    requires Perm(buf->dim, 1\2) ** buf->dim != NULL;
    requires 0 <= d && d < \pointer_length(buf->dim);
    requires Perm(&buf->dim[d], 1\2);
    requires Perm(buf->dim[d].stride, 1\2);
@*/
/*@ pure @*/ inline int _halide_buffer_get_stride_int32_t(struct halide_buffer_int32_t *buf, int d) {
    return buf->dim[d].stride;
}

/*@
inline resource buffer_int32_t(struct halide_buffer_int32_t *buf, rational p, int n_dims) = 
 buf != NULL **
 \pointer_length(buf) == 1 **
 Perm(buf, p) **
 Perm(buf->dim, p) **
 buf->dim != NULL **
 \pointer_length(buf->dim) == n_dims **
 Perm(buf->host, p) **
 buf->host != NULL;
@*/
#endif //HALIDE_BUFFER_TYPE_INT32_T
#ifndef HALIDE_BUFFER_TYPE_FLOAT
#define HALIDE_BUFFER_TYPE_FLOAT
struct halide_buffer_float {

    /** The dimensionality of the buffer. */
    int32_t dimensions;

    /** The shape of the buffer. Halide does not own this array - you
     * must manage the memory for it yourself. */
    struct halide_dimension_t *dim;

    /** A pointer to the start of the data in main memory. In terms of
     * the Halide coordinate system, this is the address of the min
     * coordinates (defined below). */

    float *host;
};

/*@ 
 requires buf != NULL ** \pointer_length(buf) == 1 ** Perm(buf, 1\2);
 requires Perm(buf->host, 1\2);
 @*/
/*@ pure @*/ inline float *_halide_buffer_get_host_float(struct halide_buffer_float *buf) {
    return buf->host;
}

/*@ 
    requires buf != NULL ** \pointer_length(buf) == 1 ** Perm(buf, 1\2);
    requires Perm(buf->dim, 1\2) ** buf->dim != NULL;
    requires 0 <= d && d < \pointer_length(buf->dim);
    requires Perm(&buf->dim[d], 1\2);
    requires Perm(buf->dim[d].min, 1\2);
@*/
/*@ pure @*/ inline int _halide_buffer_get_min_float(struct halide_buffer_float *buf, int d) {
    return buf->dim[d].min;
}

/*@ 
    requires buf != NULL ** \pointer_length(buf) == 1 ** Perm(buf, 1\2);
    requires Perm(buf->dim, 1\2) ** buf->dim != NULL;
    requires 0 <= d && d < \pointer_length(buf->dim);
    requires Perm(&buf->dim[d], 1\2);
    requires Perm(buf->dim[d].min, 1\2) ** Perm(buf->dim[d].extent, 1\2);
@*/
/*@ pure @*/ inline int _halide_buffer_get_max_float(struct halide_buffer_float *buf, int d) {
    return buf->dim[d].min + buf->dim[d].extent - 1;
}

/*@ 
    requires buf != NULL ** \pointer_length(buf) == 1 ** Perm(buf, 1\2);
    requires Perm(buf->dim, 1\2) ** buf->dim != NULL;
    requires 0 <= d && d < \pointer_length(buf->dim);
    requires Perm(&buf->dim[d], 1\2);
    requires Perm(buf->dim[d].extent, 1\2);
@*/
/*@ pure @*/ inline int _halide_buffer_get_extent_float(struct halide_buffer_float *buf, int d) {
    return buf->dim[d].extent;
}

/*@ 
    requires buf != NULL ** \pointer_length(buf) == 1 ** Perm(buf, 1\2);
    requires Perm(buf->dim, 1\2) ** buf->dim != NULL;
    requires 0 <= d && d < \pointer_length(buf->dim);
    requires Perm(&buf->dim[d], 1\2);
    requires Perm(buf->dim[d].stride, 1\2);
@*/
/*@ pure @*/ inline int _halide_buffer_get_stride_float(struct halide_buffer_float *buf, int d) {
    return buf->dim[d].stride;
}

/*@
inline resource buffer_float(struct halide_buffer_float *buf, rational p, int n_dims) = 
 buf != NULL **
 \pointer_length(buf) == 1 **
 Perm(buf, p) **
 Perm(buf->dim, p) **
 buf->dim != NULL **
 \pointer_length(buf->dim) == n_dims **
 Perm(buf->host, p) **
 buf->host != NULL;
@*/
#endif //HALIDE_BUFFER_TYPE_FLOAT










#ifdef __cplusplus
extern "C" {
#endif

/*@
  resource float_perm(float* xs) = xs != NULL
    ** (\forall* int i; 0 <= i && i < \pointer_length(xs); Perm({:&xs[i]:}, write));

  resource double_perm(double* xs) = xs != NULL 
    ** (\forall* int i; 0 <= i && i < \pointer_length(xs); Perm({:&xs[i]:}, write));

  resource int_perm(int* xs) = xs != NULL 
    ** (\forall* int i; 0 <= i && i < \pointer_length(xs); Perm({:&xs[i]:}, write));

  resource int_perm_bound(int* xs, int lo, int hi) = xs != NULL 
    ** (\forall* int i; 0 <= i && i < \pointer_length(xs); Perm({:&xs[i]:}, write))
    ** (\forall int i; 0 <= i && i <\pointer_length(xs); lo <= {:xs[i]:} && {:xs[i]:} < hi);

  resource denominator_r(int a, int a_min, int a_extent, int a_stride,
                         int si, int si_min, int si_extent, int si_stride,
                         int i, int i_min, int i_extent, int i_stride,
                         float* data) =
    (a >= a_min && a < a_min + a_extent &&
    si >= si_min && si < si_min + si_extent &&
    i >= i_min && i < i_min + i_extent &&
    a_extent > 0 && a_stride > 0 &&
    si_extent > 0 && si_stride > 0 &&
    i_extent > 0 && i_stride > 0 &&
    a_stride >= si_extent * si_stride &&
    si_stride >= i_extent * i_stride &&
    data != NULL && \pointer_length(data) == a_stride*a_extent) **
    Perm(&data[(a-a_min)*a_stride + (si-si_min)*si_stride + (i-i_min)*i_stride], write);

  ghost
  requires a >= a_min && a < a_min + a_extent &&
    si >= si_min && si < si_min + si_extent &&
    i >= i_min && i < i_min + i_extent &&
    a_extent > 0 && a_stride > 0 &&
    si_extent > 0 && si_stride > 0 &&
    i_extent > 0 && i_stride > 0 &&
    a_stride >= si_extent * si_stride &&
    si_stride >= i_extent * i_stride &&
    data != NULL && \pointer_length(data) == a_stride*a_extent;
  requires (\forall* int j; 0 <= j && j < a_stride*a_extent; Perm({:&data[j]:}, write));
  ensures (\forall* int a, int si, int i; a >= a_min && a < a_min + a_extent &&
    si >= si_min && si < si_min + si_extent &&
    i >= i_min && i < i_min + i_extent;
    {:denominator_r(a, a_min, a_extent, a_stride, si, si_min, si_extent, si_stride, i, i_min, i_extent, i_stride, data):});
  void fold_denominator_r(int a, int a_min, int a_extent, int a_stride,
                          int si, int si_min, int si_extent, int si_stride,
                          int i, int i_min, int i_extent, int i_stride,
                          float* data){
     for(int a0 = a_min; a0 < a_min + a_extent; a0++){
        loop_invariant (\forall* int si, int i;
        si >= si_min && si < si_min + si_extent &&
        i >= i_min && i < i_min + i_extent;
        {:denominator_r(a, a_min, a_extent, a_stride, si, si_min, si_extent, si_stride, i, i_min, i_extent, i_stride, data):});
       for(int si0 = si_min; si0 < si_min + si_extent; si0++){
          loop_invariant (\forall* int i;
            i >= i_min && i <= i0 ;
            {:denominator_r(a, a_min, a_extent, a_stride, si, si_min, si_extent, si_stride, i, i_min, i_extent, i_stride, data):});
         for(int i0 = i_min; i0 < i_min + i_extent; i0++){
           fold denominator_r(a0, a_min, a_extent, a_stride, si0, si_min, si_extent, si_stride, i0, i_min, i_extent, i_stride, data);
         }
       }
     }
    }  
@*/


/*@
 context buffer_double(_sol__buffer, 1\2, 4);
 context dim_perm(_sol__buffer->dim, 1\2, 0);
 context dim_perm(_sol__buffer->dim, 1\2, 1);
 context dim_perm(_sol__buffer->dim, 1\2, 2);
 context dim_perm(_sol__buffer->dim, 1\2, 3);
 context \pointer_length(_sol__buffer->host) == _sol__buffer->dim[3].extent * _sol__buffer->dim[3].stride;
 context buffer_int32_t(_solution_map_buffer, 1\2, 1);
 context dim_perm(_solution_map_buffer->dim, 1\2, 0);
 context \pointer_length(_solution_map_buffer->host) == _solution_map_buffer->dim[0].extent * _solution_map_buffer->dim[0].stride;
 context buffer_int32_t(_ant1_buffer, 1\2, 1);
 context dim_perm(_ant1_buffer->dim, 1\2, 0);
 context \pointer_length(_ant1_buffer->host) == _ant1_buffer->dim[0].extent * _ant1_buffer->dim[0].stride;
 context buffer_int32_t(_ant2_buffer, 1\2, 1);
 context dim_perm(_ant2_buffer->dim, 1\2, 0);
 context \pointer_length(_ant2_buffer->host) == _ant2_buffer->dim[0].extent * _ant2_buffer->dim[0].stride;
 context buffer_float(_model__buffer, 1\2, 4);
 context dim_perm(_model__buffer->dim, 1\2, 0);
 context dim_perm(_model__buffer->dim, 1\2, 1);
 context dim_perm(_model__buffer->dim, 1\2, 2);
 context dim_perm(_model__buffer->dim, 1\2, 3);
 context \pointer_length(_model__buffer->host) == _model__buffer->dim[3].extent * _model__buffer->dim[3].stride;
 context buffer_float(_v_res_in_buffer, 1\2, 4);
 context dim_perm(_v_res_in_buffer->dim, 1\2, 0);
 context dim_perm(_v_res_in_buffer->dim, 1\2, 1);
 context dim_perm(_v_res_in_buffer->dim, 1\2, 2);
 context dim_perm(_v_res_in_buffer->dim, 1\2, 3);
 context \pointer_length(_v_res_in_buffer->host) == _v_res_in_buffer->dim[3].extent * _v_res_in_buffer->dim[3].stride;
 context buffer_double(_next_solutions_complex_buffer, 1\2, 4);
 context dim_perm(_next_solutions_complex_buffer->dim, 1\2, 0);
 context dim_perm(_next_solutions_complex_buffer->dim, 1\2, 1);
 context dim_perm(_next_solutions_complex_buffer->dim, 1\2, 2);
 context dim_perm(_next_solutions_complex_buffer->dim, 1\2, 3);
 context \pointer_length(_next_solutions_complex_buffer->host) == _next_solutions_complex_buffer->dim[3].extent * _next_solutions_complex_buffer->dim[3].stride;
 context _ant1_buffer->host != _solution_map_buffer->host;
 context _ant2_buffer->host != _solution_map_buffer->host;
 context _ant2_buffer->host != _ant1_buffer->host;
 context _model__buffer->host != _sol__buffer->host;
 context _v_res_in_buffer->host != _sol__buffer->host;
 context _v_res_in_buffer->host != _model__buffer->host;
 context _next_solutions_complex_buffer->host != _sol__buffer->host;
 context _next_solutions_complex_buffer->host != _model__buffer->host;
 context _next_solutions_complex_buffer->host != _v_res_in_buffer->host;
 context _ant1_buffer->dim[0].min == 0 && _ant1_buffer->dim[0].extent == 230930 && _ant1_buffer->dim[0].stride == 1;
 context _ant2_buffer->dim[0].min == 0 && _ant2_buffer->dim[0].extent == 230930 && _ant2_buffer->dim[0].stride == 1;
 context _model__buffer->dim[0].min == 0 && _model__buffer->dim[0].extent == 2 && _model__buffer->dim[0].stride == 1;
 context _model__buffer->dim[1].min == 0 && _model__buffer->dim[1].extent == 2 && _model__buffer->dim[1].stride == 2;
 context _model__buffer->dim[2].min == 0 && _model__buffer->dim[2].extent == 2 && _model__buffer->dim[2].stride == 4;
 context _model__buffer->dim[3].min == 0 && _model__buffer->dim[3].extent == 230930 && _model__buffer->dim[3].stride == 8;
 context _sol__buffer->dim[0].min == 0 && _sol__buffer->dim[0].extent == 2 && _sol__buffer->dim[0].stride == 1;
 context _sol__buffer->dim[1].min == 0 && _sol__buffer->dim[1].extent == 2 && _sol__buffer->dim[1].stride == 2;
 context _sol__buffer->dim[2].min == 0 && _sol__buffer->dim[2].extent == 8 && _sol__buffer->dim[2].stride == 4;
 context _sol__buffer->dim[3].min == 0 && _sol__buffer->dim[3].extent == 50 && _sol__buffer->dim[3].stride == 32;
 context _solution_map_buffer->dim[0].min == 0 && _solution_map_buffer->dim[0].extent == 230930 && _solution_map_buffer->dim[0].stride == 1;
 context _v_res_in_buffer->dim[0].min == 0 && _v_res_in_buffer->dim[0].extent == 2 && _v_res_in_buffer->dim[0].stride == 1;
 context _v_res_in_buffer->dim[1].min == 0 && _v_res_in_buffer->dim[1].extent == 2 && _v_res_in_buffer->dim[1].stride == 2;
 context _v_res_in_buffer->dim[2].min == 0 && _v_res_in_buffer->dim[2].extent == 2 && _v_res_in_buffer->dim[2].stride == 4;
 context _v_res_in_buffer->dim[3].min == 0 && _v_res_in_buffer->dim[3].extent == 230930 && _v_res_in_buffer->dim[3].stride == 8;
 context _next_solutions_complex_buffer->dim[0].min == 0 && _next_solutions_complex_buffer->dim[0].extent == 2 && _next_solutions_complex_buffer->dim[0].stride == 1;
 context _next_solutions_complex_buffer->dim[1].min == 0 && _next_solutions_complex_buffer->dim[1].extent == 2 && _next_solutions_complex_buffer->dim[1].stride == 2;
 context _next_solutions_complex_buffer->dim[2].min == 0 && _next_solutions_complex_buffer->dim[2].extent == 3 && _next_solutions_complex_buffer->dim[2].stride == 4;
 context _next_solutions_complex_buffer->dim[3].min == 0 && _next_solutions_complex_buffer->dim[3].extent == 50 && _next_solutions_complex_buffer->dim[3].stride == 32;



 context [1\2]int_perm_bound(_ant1_buffer->host, 0, 50);
 context [1\2]int_perm_bound(_ant2_buffer->host, 0, 50);
 context [1\2]int_perm_bound(_solution_map_buffer->host, 0, 3);
 context [1\2]float_perm(_model__buffer->host);
 context [1\2]double_perm(_sol__buffer->host);
 context [1\2]float_perm(_v_res_in_buffer->host);

 context double_perm(_next_solutions_complex_buffer->host);
@*/
int SolveDirection(struct halide_buffer_double *_sol__buffer, struct halide_buffer_int32_t *_solution_map_buffer, struct halide_buffer_int32_t *_ant1_buffer, struct halide_buffer_int32_t *_ant2_buffer, struct halide_buffer_float *_model__buffer, struct halide_buffer_float *_v_res_in_buffer, int32_t _p0, int32_t _p1, int32_t _p3, int32_t _p2, int32_t _p4, struct halide_buffer_double *_next_solutions_complex_buffer) {
 int32_t* _ant1 = _halide_buffer_get_host_int32_t(_ant1_buffer);
 int32_t _ant1_min_0 = _halide_buffer_get_min_int32_t(_ant1_buffer, 0);
 int32_t _ant1_extent_0 = _halide_buffer_get_extent_int32_t(_ant1_buffer, 0);
 int32_t _ant1_stride_0 = _halide_buffer_get_stride_int32_t(_ant1_buffer, 0);
 int32_t* _ant2 = _halide_buffer_get_host_int32_t(_ant2_buffer);
 int32_t _ant2_min_0 = _halide_buffer_get_min_int32_t(_ant2_buffer, 0);
 int32_t _ant2_extent_0 = _halide_buffer_get_extent_int32_t(_ant2_buffer, 0);
 int32_t _ant2_stride_0 = _halide_buffer_get_stride_int32_t(_ant2_buffer, 0);
 float* _model_ = _halide_buffer_get_host_float(_model__buffer);
 int32_t _model__min_0 = _halide_buffer_get_min_float(_model__buffer, 0);
 int32_t _model__extent_0 = _halide_buffer_get_extent_float(_model__buffer, 0);
 int32_t _model__stride_0 = _halide_buffer_get_stride_float(_model__buffer, 0);
 int32_t _model__min_1 = _halide_buffer_get_min_float(_model__buffer, 1);
 int32_t _model__extent_1 = _halide_buffer_get_extent_float(_model__buffer, 1);
 int32_t _model__stride_1 = _halide_buffer_get_stride_float(_model__buffer, 1);
 int32_t _model__min_2 = _halide_buffer_get_min_float(_model__buffer, 2);
 int32_t _model__extent_2 = _halide_buffer_get_extent_float(_model__buffer, 2);
 int32_t _model__stride_2 = _halide_buffer_get_stride_float(_model__buffer, 2);
 int32_t _model__min_3 = _halide_buffer_get_min_float(_model__buffer, 3);
 int32_t _model__extent_3 = _halide_buffer_get_extent_float(_model__buffer, 3);
 int32_t _model__stride_3 = _halide_buffer_get_stride_float(_model__buffer, 3);
 double* _next_solutions_complex = _halide_buffer_get_host_double(_next_solutions_complex_buffer);
 int32_t _next_solutions_complex_min_0 = _halide_buffer_get_min_double(_next_solutions_complex_buffer, 0);
 int32_t _next_solutions_complex_extent_0 = _halide_buffer_get_extent_double(_next_solutions_complex_buffer, 0);
 int32_t _next_solutions_complex_stride_0 = _halide_buffer_get_stride_double(_next_solutions_complex_buffer, 0);
 int32_t _next_solutions_complex_min_1 = _halide_buffer_get_min_double(_next_solutions_complex_buffer, 1);
 int32_t _next_solutions_complex_extent_1 = _halide_buffer_get_extent_double(_next_solutions_complex_buffer, 1);
 int32_t _next_solutions_complex_stride_1 = _halide_buffer_get_stride_double(_next_solutions_complex_buffer, 1);
 int32_t _next_solutions_complex_min_2 = _halide_buffer_get_min_double(_next_solutions_complex_buffer, 2);
 int32_t _next_solutions_complex_extent_2 = _halide_buffer_get_extent_double(_next_solutions_complex_buffer, 2);
 int32_t _next_solutions_complex_stride_2 = _halide_buffer_get_stride_double(_next_solutions_complex_buffer, 2);
 int32_t _next_solutions_complex_min_3 = _halide_buffer_get_min_double(_next_solutions_complex_buffer, 3);
 int32_t _next_solutions_complex_extent_3 = _halide_buffer_get_extent_double(_next_solutions_complex_buffer, 3);
 int32_t _next_solutions_complex_stride_3 = _halide_buffer_get_stride_double(_next_solutions_complex_buffer, 3);
 double* _sol_ = _halide_buffer_get_host_double(_sol__buffer);
 int32_t _sol__min_0 = _halide_buffer_get_min_double(_sol__buffer, 0);
 int32_t _sol__extent_0 = _halide_buffer_get_extent_double(_sol__buffer, 0);
 int32_t _sol__stride_0 = _halide_buffer_get_stride_double(_sol__buffer, 0);
 int32_t _sol__min_1 = _halide_buffer_get_min_double(_sol__buffer, 1);
 int32_t _sol__extent_1 = _halide_buffer_get_extent_double(_sol__buffer, 1);
 int32_t _sol__stride_1 = _halide_buffer_get_stride_double(_sol__buffer, 1);
 int32_t _sol__min_2 = _halide_buffer_get_min_double(_sol__buffer, 2);
 int32_t _sol__extent_2 = _halide_buffer_get_extent_double(_sol__buffer, 2);
 int32_t _sol__stride_2 = _halide_buffer_get_stride_double(_sol__buffer, 2);
 int32_t _sol__min_3 = _halide_buffer_get_min_double(_sol__buffer, 3);
 int32_t _sol__extent_3 = _halide_buffer_get_extent_double(_sol__buffer, 3);
 int32_t _sol__stride_3 = _halide_buffer_get_stride_double(_sol__buffer, 3);
 int32_t* _solution_map = _halide_buffer_get_host_int32_t(_solution_map_buffer);
 int32_t _solution_map_min_0 = _halide_buffer_get_min_int32_t(_solution_map_buffer, 0);
 int32_t _solution_map_extent_0 = _halide_buffer_get_extent_int32_t(_solution_map_buffer, 0);
 int32_t _solution_map_stride_0 = _halide_buffer_get_stride_int32_t(_solution_map_buffer, 0);
 float* _v_res_in = _halide_buffer_get_host_float(_v_res_in_buffer);
 int32_t _v_res_in_min_0 = _halide_buffer_get_min_float(_v_res_in_buffer, 0);
 int32_t _v_res_in_extent_0 = _halide_buffer_get_extent_float(_v_res_in_buffer, 0);
 int32_t _v_res_in_stride_0 = _halide_buffer_get_stride_float(_v_res_in_buffer, 0);
 int32_t _v_res_in_min_1 = _halide_buffer_get_min_float(_v_res_in_buffer, 1);
 int32_t _v_res_in_extent_1 = _halide_buffer_get_extent_float(_v_res_in_buffer, 1);
 int32_t _v_res_in_stride_1 = _halide_buffer_get_stride_float(_v_res_in_buffer, 1);
 int32_t _v_res_in_min_2 = _halide_buffer_get_min_float(_v_res_in_buffer, 2);
 int32_t _v_res_in_extent_2 = _halide_buffer_get_extent_float(_v_res_in_buffer, 2);
 int32_t _v_res_in_stride_2 = _halide_buffer_get_stride_float(_v_res_in_buffer, 2);
 int32_t _v_res_in_min_3 = _halide_buffer_get_min_float(_v_res_in_buffer, 3);
 int32_t _v_res_in_extent_3 = _halide_buffer_get_extent_float(_v_res_in_buffer, 3);
 int32_t _v_res_in_stride_3 = _halide_buffer_get_stride_float(_v_res_in_buffer, 3);
 halide_unused((_ant1_stride_0 == 1));
 halide_unused((_ant1_min_0 == 0));
 halide_unused((_ant1_extent_0 == 230930));
 halide_unused((_ant2_stride_0 == 1));
 halide_unused((_ant2_min_0 == 0));
 halide_unused((_ant2_extent_0 == 230930));
 halide_unused((_model__stride_0 == 1));
 halide_unused((_model__min_0 == 0));
 halide_unused((_model__extent_0 == 2));
 halide_unused((_model__stride_1 == 2));
 halide_unused((_model__min_1 == 0));
 halide_unused((_model__extent_1 == 2));
 halide_unused((_model__stride_2 == 4));
 halide_unused((_model__min_2 == 0));
 halide_unused((_model__extent_2 == 2));
 halide_unused((_model__stride_3 == 8));
 halide_unused((_model__min_3 == 0));
 halide_unused((_model__extent_3 == 230930));
 halide_unused((_next_solutions_complex_stride_0 == 1));
 halide_unused((_next_solutions_complex_min_0 == 0));
 halide_unused((_next_solutions_complex_extent_0 == 2));
 halide_unused((_next_solutions_complex_stride_1 == 2));
 halide_unused((_next_solutions_complex_min_1 == 0));
 halide_unused((_next_solutions_complex_extent_1 == 2));
 halide_unused((_next_solutions_complex_stride_2 == 4));
 halide_unused((_next_solutions_complex_min_2 == 0));
 halide_unused((_next_solutions_complex_extent_2 == 3));
 halide_unused((_next_solutions_complex_stride_3 == 32));
 halide_unused((_next_solutions_complex_min_3 == 0));
 halide_unused((_next_solutions_complex_extent_3 == 50));
 halide_unused((_sol__stride_0 == 1));
 halide_unused((_sol__min_0 == 0));
 halide_unused((_sol__extent_0 == 2));
 halide_unused((_sol__stride_1 == 2));
 halide_unused((_sol__min_1 == 0));
 halide_unused((_sol__extent_1 == 2));
 halide_unused((_sol__stride_2 == 4));
 halide_unused((_sol__min_2 == 0));
 halide_unused((_sol__extent_2 == 8));
 halide_unused((_sol__stride_3 == 32));
 halide_unused((_sol__min_3 == 0));
 halide_unused((_sol__extent_3 == 50));
 halide_unused((_solution_map_stride_0 == 1));
 halide_unused((_solution_map_min_0 == 0));
 halide_unused((_solution_map_extent_0 == 230930));
 halide_unused((_v_res_in_stride_0 == 1));
 halide_unused((_v_res_in_min_0 == 0));
 halide_unused((_v_res_in_extent_0 == 2));
 halide_unused((_v_res_in_stride_1 == 2));
 halide_unused((_v_res_in_min_1 == 0));
 halide_unused((_v_res_in_extent_1 == 2));
 halide_unused((_v_res_in_stride_2 == 4));
 halide_unused((_v_res_in_min_2 == 0));
 halide_unused((_v_res_in_extent_2 == 2));
 halide_unused((_v_res_in_stride_3 == 8));
 halide_unused((_v_res_in_min_3 == 0));
 halide_unused((_v_res_in_extent_3 == 230930));
 {
  int64_t _255 = 230930;
  float *_cor_model_2_0 = (float  *)malloc(sizeof(float )*_255);
  //@ fold float_perm(_cor_model_2_0);
  {
   int64_t _256 = 230930;
   float *_cor_model_2_1 = (float  *)malloc(sizeof(float )*_256);
   //@ fold float_perm(_cor_model_2_1);
   {
    int64_t _257 = 230930;
    float *_cor_model_2_2 = (float  *)malloc(sizeof(float )*_257);
    //@ fold float_perm(_cor_model_2_2);
    {
     int64_t _258 = 230930;
     float *_cor_model_2_3 = (float  *)malloc(sizeof(float )*_258);
     //@ fold float_perm(_cor_model_2_3);
     {
      int64_t _259 = 230930;
      float *_cor_model_2_4 = (float  *)malloc(sizeof(float )*_259);
      //@ fold float_perm(_cor_model_2_4);
      {
       int64_t _260 = 230930;
       float *_cor_model_2_5 = (float  *)malloc(sizeof(float )*_260);
       //@ fold float_perm(_cor_model_2_5);
       {
        int64_t _261 = 230930;
        float *_cor_model_2_6 = (float  *)malloc(sizeof(float )*_261);
        //@ fold float_perm(_cor_model_2_6);
        {
         int64_t _262 = 230930;
         float *_cor_model_2_7 = (float  *)malloc(sizeof(float )*_262);
         //@ fold float_perm(_cor_model_2_7);
         // produce cor_model_2
         /*@
          loop_invariant 0 <= _cor_model_2_s0_vis && _cor_model_2_s0_vis <= 0 + 230930;
          loop_invariant [1\2]int_perm_bound(_ant1, 0, 50);
          
          
          loop_invariant [1\2]float_perm(_model_);

          
          loop_invariant [1\2]double_perm(_sol_);          
          loop_invariant [1\2]int_perm_bound(_solution_map, 0, 3);
          
          loop_invariant float_perm(_cor_model_2_0);
          loop_invariant float_perm(_cor_model_2_1);
          loop_invariant float_perm(_cor_model_2_2);
          loop_invariant float_perm(_cor_model_2_3);
          loop_invariant float_perm(_cor_model_2_4);
          loop_invariant float_perm(_cor_model_2_5);
          loop_invariant float_perm(_cor_model_2_6);
          loop_invariant float_perm(_cor_model_2_7);
         @*/
         for (int _cor_model_2_s0_vis = 0; _cor_model_2_s0_vis < 0 + 230930; _cor_model_2_s0_vis++)
         {
//@unfold [1\2]int_perm_bound(_solution_map, 0, 3);
          int32_t _263 = _solution_map[_cor_model_2_s0_vis];
//@fold [1\2]int_perm_bound(_solution_map, 0, 3);
//@unfold [1\2]int_perm_bound(_ant1, 0, 50);
          int32_t _264 = _ant1[_cor_model_2_s0_vis];
//@fold [1\2]int_perm_bound(_ant1, 0, 50);
          int32_t _t12696 = (_263 + (_264 * 8));
//@unfold [1\2]float_perm(_model_);
          float _265 = _model_[(_cor_model_2_s0_vis * 8)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
          double _266 = _sol_[(_t12696 * 4)];
//@fold [1\2]double_perm(_sol_);
          float _267 = (float)(_266);
//@unfold [1\2]float_perm(_model_);
          float _268 = _model_[((_cor_model_2_s0_vis * 8) + 1)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
          double _269 = _sol_[((_t12696 * 4) + 1)];
//@fold [1\2]double_perm(_sol_);
          float _270 = (float)(_269);
//@unfold float_perm(_cor_model_2_0);
          _cor_model_2_0[_cor_model_2_s0_vis] = ((_265 * _267) - (_268 * _270));
//@fold float_perm(_cor_model_2_0);
//@unfold [1\2]float_perm(_model_);
          float _271 = _model_[((_cor_model_2_s0_vis * 8) + 1)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
          double _272 = _sol_[(_t12696 * 4)];
//@fold [1\2]double_perm(_sol_);
          float _273 = (float)(_272);
//@unfold [1\2]float_perm(_model_);
          float _274 = _model_[(_cor_model_2_s0_vis * 8)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
          double _275 = _sol_[((_t12696 * 4) + 1)];
//@fold [1\2]double_perm(_sol_);
          float _276 = (float)(_275);
//@unfold float_perm(_cor_model_2_1);
          _cor_model_2_1[_cor_model_2_s0_vis] = ((_271 * _273) + (_274 * _276));
//@fold float_perm(_cor_model_2_1);
//@unfold [1\2]float_perm(_model_);
          float _277 = _model_[((_cor_model_2_s0_vis * 8) + 2)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
          double _278 = _sol_[(_t12696 * 4)];
//@fold [1\2]double_perm(_sol_);
          float _279 = (float)(_278);
//@unfold [1\2]float_perm(_model_);
          float _280 = _model_[((_cor_model_2_s0_vis * 8) + 3)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
          double _281 = _sol_[((_t12696 * 4) + 1)];
//@fold [1\2]double_perm(_sol_);
          float _282 = (float)(_281);
//@unfold float_perm(_cor_model_2_2);
          _cor_model_2_2[_cor_model_2_s0_vis] = ((_277 * _279) - (_280 * _282));
//@fold float_perm(_cor_model_2_2);
//@unfold [1\2]float_perm(_model_);
          float _283 = _model_[((_cor_model_2_s0_vis * 8) + 3)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
          double _284 = _sol_[(_t12696 * 4)];
//@fold [1\2]double_perm(_sol_);
          float _285 = (float)(_284);
//@unfold [1\2]float_perm(_model_);
          float _286 = _model_[((_cor_model_2_s0_vis * 8) + 2)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
          double _287 = _sol_[((_t12696 * 4) + 1)];
//@fold [1\2]double_perm(_sol_);
          float _288 = (float)(_287);
//@unfold float_perm(_cor_model_2_3);
          _cor_model_2_3[_cor_model_2_s0_vis] = ((_283 * _285) + (_286 * _288));
//@fold float_perm(_cor_model_2_3);
//@unfold [1\2]float_perm(_model_);
          float _289 = _model_[((_cor_model_2_s0_vis * 8) + 4)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
          double _290 = _sol_[((_t12696 * 4) + 2)];
//@fold [1\2]double_perm(_sol_);
          float _291 = (float)(_290);
//@unfold [1\2]float_perm(_model_);
          float _292 = _model_[((_cor_model_2_s0_vis * 8) + 5)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
          double _293 = _sol_[((_t12696 * 4) + 3)];
//@fold [1\2]double_perm(_sol_);
          float _294 = (float)(_293);
//@unfold float_perm(_cor_model_2_4);
          _cor_model_2_4[_cor_model_2_s0_vis] = ((_289 * _291) - (_292 * _294));
//@fold float_perm(_cor_model_2_4);
//@unfold [1\2]float_perm(_model_);
          float _295 = _model_[((_cor_model_2_s0_vis * 8) + 5)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
          double _296 = _sol_[((_t12696 * 4) + 2)];
//@fold [1\2]double_perm(_sol_);
          float _297 = (float)(_296);
//@unfold [1\2]float_perm(_model_);
          float _298 = _model_[((_cor_model_2_s0_vis * 8) + 4)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
          double _299 = _sol_[((_t12696 * 4) + 3)];
//@fold [1\2]double_perm(_sol_);
          float _300 = (float)(_299);
//@unfold float_perm(_cor_model_2_5);
          _cor_model_2_5[_cor_model_2_s0_vis] = ((_295 * _297) + (_298 * _300));
//@fold float_perm(_cor_model_2_5);
//@unfold [1\2]float_perm(_model_);
          float _301 = _model_[((_cor_model_2_s0_vis * 8) + 6)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
          double _302 = _sol_[((_t12696 * 4) + 2)];
//@fold [1\2]double_perm(_sol_);
          float _303 = (float)(_302);
//@unfold [1\2]float_perm(_model_);
          float _304 = _model_[((_cor_model_2_s0_vis * 8) + 7)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
          double _305 = _sol_[((_t12696 * 4) + 3)];
//@fold [1\2]double_perm(_sol_);
          float _306 = (float)(_305);
//@unfold float_perm(_cor_model_2_6);
          _cor_model_2_6[_cor_model_2_s0_vis] = ((_301 * _303) - (_304 * _306));
//@fold float_perm(_cor_model_2_6);
//@unfold [1\2]float_perm(_model_);
          float _307 = _model_[((_cor_model_2_s0_vis * 8) + 7)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
          double _308 = _sol_[((_t12696 * 4) + 2)];
//@fold [1\2]double_perm(_sol_);
          float _309 = (float)(_308);
//@unfold [1\2]float_perm(_model_);
          float _310 = _model_[((_cor_model_2_s0_vis * 8) + 6)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
          double _311 = _sol_[((_t12696 * 4) + 3)];
//@fold [1\2]double_perm(_sol_);
          float _312 = (float)(_311);
//@unfold float_perm(_cor_model_2_7);
          _cor_model_2_7[_cor_model_2_s0_vis] = ((_307 * _309) + (_310 * _312));
//@fold float_perm(_cor_model_2_7);
         } // for _cor_model_2_s0_vis
         {
          int64_t _313 = 230930;
          float *_cor_model_transp_1_0 = (float  *)malloc(sizeof(float )*_313);
          //@ fold float_perm(_cor_model_transp_1_0);
          {
           int64_t _314 = 230930;
           float *_cor_model_transp_1_1 = (float  *)malloc(sizeof(float )*_314);
           //@ fold float_perm(_cor_model_transp_1_1);
           {
            int64_t _315 = 230930;
            float *_cor_model_transp_1_2 = (float  *)malloc(sizeof(float )*_315);
            //@ fold float_perm(_cor_model_transp_1_2);
            {
             int64_t _316 = 230930;
             float *_cor_model_transp_1_3 = (float  *)malloc(sizeof(float )*_316);
             //@ fold float_perm(_cor_model_transp_1_3);
             {
              int64_t _317 = 230930;
              float *_cor_model_transp_1_4 = (float  *)malloc(sizeof(float )*_317);
              //@ fold float_perm(_cor_model_transp_1_4);
              {
               int64_t _318 = 230930;
               float *_cor_model_transp_1_5 = (float  *)malloc(sizeof(float )*_318);
               //@ fold float_perm(_cor_model_transp_1_5);
               {
                int64_t _319 = 230930;
                float *_cor_model_transp_1_6 = (float  *)malloc(sizeof(float )*_319);
                //@ fold float_perm(_cor_model_transp_1_6);
                {
                 int64_t _320 = 230930;
                 float *_cor_model_transp_1_7 = (float  *)malloc(sizeof(float )*_320);
                 //@ fold float_perm(_cor_model_transp_1_7);
                 // produce cor_model_transp_1
                 /*@
                  loop_invariant 0 <= _cor_model_transp_1_s0_vis && _cor_model_transp_1_s0_vis <= 0 + 230930;
                  loop_invariant [1\2]int_perm_bound(_ant2, 0, 50);
                  
                  
                  loop_invariant [1\2]float_perm(_model_);

                  
                  loop_invariant [1\2]double_perm(_sol_);                  
                  loop_invariant [1\2]int_perm_bound(_solution_map, 0, 3);

                  loop_invariant float_perm(_cor_model_transp_1_0);
                  loop_invariant float_perm(_cor_model_transp_1_1);
                  loop_invariant float_perm(_cor_model_transp_1_2);
                  loop_invariant float_perm(_cor_model_transp_1_3);
                  loop_invariant float_perm(_cor_model_transp_1_4);
                  loop_invariant float_perm(_cor_model_transp_1_5);
                  loop_invariant float_perm(_cor_model_transp_1_6);
                  loop_invariant float_perm(_cor_model_transp_1_7);
                 @*/
                 for (int _cor_model_transp_1_s0_vis = 0; _cor_model_transp_1_s0_vis < 0 + 230930; _cor_model_transp_1_s0_vis++)
                 {
//@unfold [1\2]int_perm_bound(_solution_map, 0, 3);
                  int32_t _321 = _solution_map[_cor_model_transp_1_s0_vis];
//@fold [1\2]int_perm_bound(_solution_map, 0, 3);
//@unfold [1\2]int_perm_bound(_ant2, 0, 50);
                  int32_t _322 = _ant2[_cor_model_transp_1_s0_vis];
//@fold [1\2]int_perm_bound(_ant2, 0, 50);
                  int32_t _t12703 = (_321 + (_322 * 8));
//@unfold [1\2]float_perm(_model_);
                  float _323 = _model_[(_cor_model_transp_1_s0_vis * 8)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
                  double _324 = _sol_[(_t12703 * 4)];
//@fold [1\2]double_perm(_sol_);
                  float _325 = (float)(_324);
//@unfold [1\2]float_perm(_model_);
                  float _326 = _model_[((_cor_model_transp_1_s0_vis * 8) + 1)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
                  double _327 = _sol_[((_t12703 * 4) + 1)];
//@fold [1\2]double_perm(_sol_);
                  float _328 = (float)(_327);
//@unfold float_perm(_cor_model_transp_1_0);
                  _cor_model_transp_1_0[_cor_model_transp_1_s0_vis] = ((_323 * _325) - ((0.000000 - _326) * _328));
//@fold float_perm(_cor_model_transp_1_0);
//@unfold [1\2]float_perm(_model_);
                  float _329 = _model_[((_cor_model_transp_1_s0_vis * 8) + 1)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
                  double _330 = _sol_[(_t12703 * 4)];
//@fold [1\2]double_perm(_sol_);
                  float _331 = (float)(_330);
//@unfold [1\2]float_perm(_model_);
                  float _332 = _model_[(_cor_model_transp_1_s0_vis * 8)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
                  double _333 = _sol_[((_t12703 * 4) + 1)];
//@fold [1\2]double_perm(_sol_);
                  float _334 = (float)(_333);
//@unfold float_perm(_cor_model_transp_1_1);
                  _cor_model_transp_1_1[_cor_model_transp_1_s0_vis] = (((0.000000 - _329) * _331) + (_332 * _334));
//@fold float_perm(_cor_model_transp_1_1);
//@unfold [1\2]float_perm(_model_);
                  float _335 = _model_[((_cor_model_transp_1_s0_vis * 8) + 4)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
                  double _336 = _sol_[(_t12703 * 4)];
//@fold [1\2]double_perm(_sol_);
                  float _337 = (float)(_336);
//@unfold [1\2]float_perm(_model_);
                  float _338 = _model_[((_cor_model_transp_1_s0_vis * 8) + 5)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
                  double _339 = _sol_[((_t12703 * 4) + 1)];
//@fold [1\2]double_perm(_sol_);
                  float _340 = (float)(_339);
//@unfold float_perm(_cor_model_transp_1_2);
                  _cor_model_transp_1_2[_cor_model_transp_1_s0_vis] = ((_335 * _337) - ((0.000000 - _338) * _340));
//@fold float_perm(_cor_model_transp_1_2);
//@unfold [1\2]float_perm(_model_);
                  float _341 = _model_[((_cor_model_transp_1_s0_vis * 8) + 5)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
                  double _342 = _sol_[(_t12703 * 4)];
//@fold [1\2]double_perm(_sol_);
                  float _343 = (float)(_342);
//@unfold [1\2]float_perm(_model_);
                  float _344 = _model_[((_cor_model_transp_1_s0_vis * 8) + 4)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
                  double _345 = _sol_[((_t12703 * 4) + 1)];
//@fold [1\2]double_perm(_sol_);
                  float _346 = (float)(_345);
//@unfold float_perm(_cor_model_transp_1_3);
                  _cor_model_transp_1_3[_cor_model_transp_1_s0_vis] = (((0.000000 - _341) * _343) + (_344 * _346));
//@fold float_perm(_cor_model_transp_1_3);
//@unfold [1\2]float_perm(_model_);
                  float _347 = _model_[((_cor_model_transp_1_s0_vis * 8) + 2)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
                  double _348 = _sol_[((_t12703 * 4) + 2)];
//@fold [1\2]double_perm(_sol_);
                  float _349 = (float)(_348);
//@unfold [1\2]float_perm(_model_);
                  float _350 = _model_[((_cor_model_transp_1_s0_vis * 8) + 3)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
                  double _351 = _sol_[((_t12703 * 4) + 3)];
//@fold [1\2]double_perm(_sol_);
                  float _352 = (float)(_351);
//@unfold float_perm(_cor_model_transp_1_4);
                  _cor_model_transp_1_4[_cor_model_transp_1_s0_vis] = ((_347 * _349) - ((0.000000 - _350) * _352));
//@fold float_perm(_cor_model_transp_1_4);
//@unfold [1\2]float_perm(_model_);
                  float _353 = _model_[((_cor_model_transp_1_s0_vis * 8) + 3)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
                  double _354 = _sol_[((_t12703 * 4) + 2)];
//@fold [1\2]double_perm(_sol_);
                  float _355 = (float)(_354);
//@unfold [1\2]float_perm(_model_);
                  float _356 = _model_[((_cor_model_transp_1_s0_vis * 8) + 2)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
                  double _357 = _sol_[((_t12703 * 4) + 3)];
//@fold [1\2]double_perm(_sol_);
                  float _358 = (float)(_357);
//@unfold float_perm(_cor_model_transp_1_5);
                  _cor_model_transp_1_5[_cor_model_transp_1_s0_vis] = (((0.000000 - _353) * _355) + (_356 * _358));
//@fold float_perm(_cor_model_transp_1_5);
//@unfold [1\2]float_perm(_model_);
                  float _359 = _model_[((_cor_model_transp_1_s0_vis * 8) + 6)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
                  double _360 = _sol_[((_t12703 * 4) + 2)];
//@fold [1\2]double_perm(_sol_);
                  float _361 = (float)(_360);
//@unfold [1\2]float_perm(_model_);
                  float _362 = _model_[((_cor_model_transp_1_s0_vis * 8) + 7)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
                  double _363 = _sol_[((_t12703 * 4) + 3)];
//@fold [1\2]double_perm(_sol_);
                  float _364 = (float)(_363);
//@unfold float_perm(_cor_model_transp_1_6);
                  _cor_model_transp_1_6[_cor_model_transp_1_s0_vis] = ((_359 * _361) - ((0.000000 - _362) * _364));
//@fold float_perm(_cor_model_transp_1_6);
//@unfold [1\2]float_perm(_model_);
                  float _365 = _model_[((_cor_model_transp_1_s0_vis * 8) + 7)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
                  double _366 = _sol_[((_t12703 * 4) + 2)];
//@fold [1\2]double_perm(_sol_);
                  float _367 = (float)(_366);
//@unfold [1\2]float_perm(_model_);
                  float _368 = _model_[((_cor_model_transp_1_s0_vis * 8) + 6)];
//@fold [1\2]float_perm(_model_);
//@unfold [1\2]double_perm(_sol_);
                  double _369 = _sol_[((_t12703 * 4) + 3)];
//@fold [1\2]double_perm(_sol_);
                  float _370 = (float)(_369);
//@unfold float_perm(_cor_model_transp_1_7);
                  _cor_model_transp_1_7[_cor_model_transp_1_s0_vis] = (((0.000000 - _365) * _367) + (_368 * _370));
//@fold float_perm(_cor_model_transp_1_7);
                 } // for _cor_model_transp_1_s0_vis
                 {
                  float _denominator__1[300];
                  //@ fold float_perm(_denominator__1);
                  // produce denominator$1
                  /*@
                   loop_invariant 0 <= _denominator__1_s0_a && _denominator__1_s0_a <= 0 + 50;
                   loop_invariant float_perm(_denominator__1);
                //    loop_invariant (\forall* int _denominator__1_s0_i_forall, int _denominator__1_s0_si_forall, int _denominator__1_s0_a_forall; 0 <= _denominator__1_s0_a_forall && _denominator__1_s0_a_forall < 50 && 0 <= _denominator__1_s0_si_forall && _denominator__1_s0_si_forall < 3 && 0 <= _denominator__1_s0_i_forall && _denominator__1_s0_i_forall < 2; Perm(&_denominator__1[(_denominator__1_s0_a_forall*3 + _denominator__1_s0_si_forall)*2 + _denominator__1_s0_i_forall], 1\1));
                  @*/
                  for (int _denominator__1_s0_a = 0; _denominator__1_s0_a < 0 + 50; _denominator__1_s0_a++)
                  {
                   int32_t _t12735 = (_denominator__1_s0_a * 6);
                   /*@
                    loop_invariant 0 <= _denominator__1_s0_si && _denominator__1_s0_si <= 0 + 3;
                    loop_invariant float_perm(_denominator__1);
                    // loop_invariant (\forall* int _denominator__1_s0_i_forall, int _denominator__1_s0_si_forall; 0 <= _denominator__1_s0_si_forall && _denominator__1_s0_si_forall < 3 && 0 <= _denominator__1_s0_i_forall && _denominator__1_s0_i_forall < 2; Perm(&_denominator__1[_denominator__1_s0_a*6 + _denominator__1_s0_si_forall*2 + _denominator__1_s0_i_forall], 1\1));
                   @*/
                   for (int _denominator__1_s0_si = 0; _denominator__1_s0_si < 0 + 3; _denominator__1_s0_si++)
                   {
                    int32_t _t12736 = ((_denominator__1_s0_si * 2) + _t12735);
                    /*@
                     loop_invariant 0 <= _denominator__1_s0_i && _denominator__1_s0_i <= 0 + 2;
                     loop_invariant float_perm(_denominator__1);
                    @*/
                    for (int _denominator__1_s0_i = 0; _denominator__1_s0_i < 0 + 2; _denominator__1_s0_i++)
                    {
                     //@ unfold float_perm(_denominator__1);
                     _denominator__1[(_denominator__1_s0_i + _t12736)] = 0.000000;
                     //@ fold float_perm(_denominator__1);
                    } // for _denominator__1_s0_i
                   } // for _denominator__1_s0_si
                  } // for _denominator__1_s0_a
                  // consume cor_model_transp_1
                  // consume cor_model_2
                  /*@
                   loop_invariant 0 <= _denominator__1_s1_i && _denominator__1_s1_i <= 0 + 2;
                   loop_invariant [1\2]int_perm_bound(_ant1, 0, 50);
                   
                   
                   loop_invariant [1\2]int_perm_bound(_ant2, 0, 50);
                   
                   
                   loop_invariant [1\2]int_perm_bound(_solution_map, 0, 3);
                   
                   loop_invariant [1\2]float_perm(_cor_model_2_0); 
                   loop_invariant [1\2]float_perm(_cor_model_2_1); 
                   loop_invariant [1\2]float_perm(_cor_model_2_2); 
                   loop_invariant [1\2]float_perm(_cor_model_2_3); 
                   loop_invariant [1\2]float_perm(_cor_model_2_4); 
                   loop_invariant [1\2]float_perm(_cor_model_2_5); 
                   loop_invariant [1\2]float_perm(_cor_model_2_6); 
                   loop_invariant [1\2]float_perm(_cor_model_2_7); 
 
                   loop_invariant [1\2]float_perm(_cor_model_transp_1_0); 
                   loop_invariant [1\2]float_perm(_cor_model_transp_1_1);
                   loop_invariant [1\2]float_perm(_cor_model_transp_1_2);
                   loop_invariant [1\2]float_perm(_cor_model_transp_1_3);
                   loop_invariant [1\2]float_perm(_cor_model_transp_1_4);
                   loop_invariant [1\2]float_perm(_cor_model_transp_1_5);
                   loop_invariant [1\2]float_perm(_cor_model_transp_1_6);
                   loop_invariant [1\2]float_perm(_cor_model_transp_1_7); 

                   loop_invariant float_perm(_denominator__1);
                //    loop_invariant (\forall* int _denominator__1_s1_si_forall, int _denominator__1_s1_a_forall, int _denominator__1_s1_i_forall; 0 <= _denominator__1_s1_i_forall && _denominator__1_s1_i_forall < 2 && 0 <= _denominator__1_s1_si_forall && _denominator__1_s1_si_forall < 3 && 0 <= _denominator__1_s1_a_forall && _denominator__1_s1_a_forall < 50; Perm(&_denominator__1[(_denominator__1_s1_a_forall*3 + _denominator__1_s1_si_forall)*2 + _denominator__1_s1_i_forall], 1\1));
                  @*/
                  for (int _denominator__1_s1_i = 0; _denominator__1_s1_i < 0 + 2; _denominator__1_s1_i++)
                  {
                   /*@
                    loop_invariant 0 <= _denominator__1_s1_rv2__y && _denominator__1_s1_rv2__y <= 0 + 230930;
                    loop_invariant [1\2]int_perm_bound(_ant1, 0, 50);
                    
                    
                    loop_invariant [1\2]int_perm_bound(_ant2, 0, 50);
                    
                    
                    loop_invariant [1\2]int_perm_bound(_solution_map, 0, 3);
                    
                    
                    loop_invariant [1\2]float_perm(_cor_model_2_0); 
                    loop_invariant [1\2]float_perm(_cor_model_2_1); 
                    loop_invariant [1\2]float_perm(_cor_model_2_2); 
                    loop_invariant [1\2]float_perm(_cor_model_2_3); 
                    loop_invariant [1\2]float_perm(_cor_model_2_4); 
                    loop_invariant [1\2]float_perm(_cor_model_2_5); 
                    loop_invariant [1\2]float_perm(_cor_model_2_6); 
                    loop_invariant [1\2]float_perm(_cor_model_2_7); 

                    loop_invariant [1\2]float_perm(_cor_model_transp_1_0); 
                    loop_invariant [1\2]float_perm(_cor_model_transp_1_1);
                    loop_invariant [1\2]float_perm(_cor_model_transp_1_2);
                    loop_invariant [1\2]float_perm(_cor_model_transp_1_3);
                    loop_invariant [1\2]float_perm(_cor_model_transp_1_4);
                    loop_invariant [1\2]float_perm(_cor_model_transp_1_5);
                    loop_invariant [1\2]float_perm(_cor_model_transp_1_6);
                    loop_invariant [1\2]float_perm(_cor_model_transp_1_7);
                   
                    loop_invariant float_perm(_denominator__1);

                    // loop_invariant (\forall* int _denominator__1_s1_si_forall, int _denominator__1_s1_a_forall; 0 <= _denominator__1_s1_si_forall && _denominator__1_s1_si_forall < 3 && 0 <= _denominator__1_s1_a_forall && _denominator__1_s1_a_forall < 50; Perm(&_denominator__1[(_denominator__1_s1_a_forall*3 + _denominator__1_s1_si_forall)*2 + _denominator__1_s1_i], 1\1));
                   @*/
                   for (int _denominator__1_s1_rv2__y = 0; _denominator__1_s1_rv2__y < 0 + 230930; _denominator__1_s1_rv2__y++)
                   {
                    /*@
                     loop_invariant 0 <= _denominator__1_s1_rv2__x && _denominator__1_s1_rv2__x <= 0 + 2;
                     loop_invariant [1\2]int_perm_bound(_ant1, 0, 50);
                     
                     
                     loop_invariant [1\2]int_perm_bound(_ant2, 0, 50);
                     
                     
                     loop_invariant [1\2]int_perm_bound(_solution_map, 0, 3);

                     loop_invariant [1\2]float_perm(_cor_model_2_0); 
                    loop_invariant [1\2]float_perm(_cor_model_2_1); 
                    loop_invariant [1\2]float_perm(_cor_model_2_2); 
                    loop_invariant [1\2]float_perm(_cor_model_2_3); 
                    loop_invariant [1\2]float_perm(_cor_model_2_4); 
                    loop_invariant [1\2]float_perm(_cor_model_2_5); 
                    loop_invariant [1\2]float_perm(_cor_model_2_6); 
                    loop_invariant [1\2]float_perm(_cor_model_2_7); 

                    loop_invariant [1\2]float_perm(_cor_model_transp_1_0); 
                    loop_invariant [1\2]float_perm(_cor_model_transp_1_1);
                    loop_invariant [1\2]float_perm(_cor_model_transp_1_2);
                    loop_invariant [1\2]float_perm(_cor_model_transp_1_3);
                    loop_invariant [1\2]float_perm(_cor_model_transp_1_4);
                    loop_invariant [1\2]float_perm(_cor_model_transp_1_5);
                    loop_invariant [1\2]float_perm(_cor_model_transp_1_6);
                    loop_invariant [1\2]float_perm(_cor_model_transp_1_7);
                   
                     loop_invariant float_perm(_denominator__1);

                    //  loop_invariant (\forall* int _denominator__1_s1_si_forall, int _denominator__1_s1_a_forall; 0 <= _denominator__1_s1_si_forall && _denominator__1_s1_si_forall < 3 && 0 <= _denominator__1_s1_a_forall && _denominator__1_s1_a_forall < 50; Perm(&_denominator__1[(_denominator__1_s1_a_forall*3 + _denominator__1_s1_si_forall)*2 + _denominator__1_s1_i], 1\1));
                    @*/
                    for (int _denominator__1_s1_rv2__x = 0; _denominator__1_s1_rv2__x < 0 + 2; _denominator__1_s1_rv2__x++)
                    {
                     {
                      float _denominator_inter__1[4];
                      // produce denominator_inter$1
//@unfold [1\2]float_perm(_cor_model_transp_1_0);
                      float _371 = _cor_model_transp_1_0[_denominator__1_s1_rv2__y];
//@fold [1\2]float_perm(_cor_model_transp_1_0);
                      float _t12524 = _371;
//@unfold [1\2]float_perm(_cor_model_transp_1_1);
                      float _372 = _cor_model_transp_1_1[_denominator__1_s1_rv2__y];
//@fold [1\2]float_perm(_cor_model_transp_1_1);
                      float _t12525 = _372;
//@unfold [1\2]float_perm(_cor_model_transp_1_4);
                      float _373 = _cor_model_transp_1_4[_denominator__1_s1_rv2__y];
//@fold [1\2]float_perm(_cor_model_transp_1_4);
                      float _t12526 = _373;
//@unfold [1\2]float_perm(_cor_model_transp_1_5);
                      float _374 = _cor_model_transp_1_5[_denominator__1_s1_rv2__y];
//@fold [1\2]float_perm(_cor_model_transp_1_5);
                      float _t12527 = _374;
                      _denominator_inter__1[0] = (((_t12524 * _t12524) + (_t12525 * _t12525)) + ((_t12526 * _t12526) + (_t12527 * _t12527)));
//@unfold [1\2]float_perm(_cor_model_transp_1_2);
                      float _375 = _cor_model_transp_1_2[_denominator__1_s1_rv2__y];
//@fold [1\2]float_perm(_cor_model_transp_1_2);
                      float _t12528 = _375;
//@unfold [1\2]float_perm(_cor_model_transp_1_3);
                      float _376 = _cor_model_transp_1_3[_denominator__1_s1_rv2__y];
//@fold [1\2]float_perm(_cor_model_transp_1_3);
                      float _t12529 = _376;
//@unfold [1\2]float_perm(_cor_model_transp_1_6);
                      float _377 = _cor_model_transp_1_6[_denominator__1_s1_rv2__y];
//@fold [1\2]float_perm(_cor_model_transp_1_6);
                      float _t12530 = _377;
//@unfold [1\2]float_perm(_cor_model_transp_1_7);
                      float _378 = _cor_model_transp_1_7[_denominator__1_s1_rv2__y];
//@fold [1\2]float_perm(_cor_model_transp_1_7);
                      float _t12531 = _378;
                      _denominator_inter__1[2] = (((_t12528 * _t12528) + (_t12529 * _t12529)) + ((_t12530 * _t12530) + (_t12531 * _t12531)));
//@unfold [1\2]float_perm(_cor_model_2_0);
                      float _379 = _cor_model_2_0[_denominator__1_s1_rv2__y];
//@fold [1\2]float_perm(_cor_model_2_0);
                      float _t12532 = _379;
//@unfold [1\2]float_perm(_cor_model_2_1);
                      float _380 = _cor_model_2_1[_denominator__1_s1_rv2__y];
//@fold [1\2]float_perm(_cor_model_2_1);
                      float _t12533 = _380;
//@unfold [1\2]float_perm(_cor_model_2_4);
                      float _381 = _cor_model_2_4[_denominator__1_s1_rv2__y];
//@fold [1\2]float_perm(_cor_model_2_4);
                      float _t12534 = _381;
//@unfold [1\2]float_perm(_cor_model_2_5);
                      float _382 = _cor_model_2_5[_denominator__1_s1_rv2__y];
//@fold [1\2]float_perm(_cor_model_2_5);
                      float _t12535 = _382;
                      _denominator_inter__1[1] = (((_t12532 * _t12532) + (_t12533 * _t12533)) + ((_t12534 * _t12534) + (_t12535 * _t12535)));
//@unfold [1\2]float_perm(_cor_model_2_2);
                      float _383 = _cor_model_2_2[_denominator__1_s1_rv2__y];
//@fold [1\2]float_perm(_cor_model_2_2);
                      float _t12536 = _383;
//@unfold [1\2]float_perm(_cor_model_2_3);
                      float _384 = _cor_model_2_3[_denominator__1_s1_rv2__y];
//@fold [1\2]float_perm(_cor_model_2_3);
                      float _t12537 = _384;
//@unfold [1\2]float_perm(_cor_model_2_6);
                      float _385 = _cor_model_2_6[_denominator__1_s1_rv2__y];
//@fold [1\2]float_perm(_cor_model_2_6);
                      float _t12538 = _385;
//@unfold [1\2]float_perm(_cor_model_2_7);
                      float _386 = _cor_model_2_7[_denominator__1_s1_rv2__y];
//@fold [1\2]float_perm(_cor_model_2_7);
                      float _t12539 = _386;
                      _denominator_inter__1[3] = (((_t12536 * _t12536) + (_t12537 * _t12537)) + ((_t12538 * _t12538) + (_t12539 * _t12539)));
                      // consume denominator_inter$1
                      //@unfold [1\2]int_perm_bound(_ant1, 0, 50);
                      int32_t _387 = _ant1[_denominator__1_s1_rv2__y];
                      //@fold [1\2]int_perm_bound(_ant1, 0, 50);
                      //@unfold [1\2]int_perm_bound(_ant2, 0, 50);
                      int32_t _388 = _ant2[_denominator__1_s1_rv2__y];
                      //@fold [1\2]int_perm_bound(_ant2, 0, 50);
                      //@unfold [1\2]int_perm_bound(_solution_map, 0, 3);
                      int32_t _389 = _solution_map[_denominator__1_s1_rv2__y];
                      //@fold [1\2]int_perm_bound(_solution_map, 0, 3);
                      int32_t _t12540 = ((((_denominator__1_s1_rv2__x == 0) ? _387 : _388) * 6) + ((_389 * 2) + _denominator__1_s1_i));
                      //@ unfold float_perm(_denominator__1);
                      float _390 = _denominator__1[_t12540];
                      float _391 = _denominator_inter__1[((_denominator__1_s1_i * 2) + _denominator__1_s1_rv2__x)];
                      _denominator__1[_t12540] = (_390 + _391);
                      //@ fold float_perm(_denominator__1);
                     } // alloc _denominator_inter__1
                    } // for _denominator__1_s1_rv2__x
                   } // for _denominator__1_s1_rv2__y
                  } // for _denominator__1_s1_i
                  {
                   float _numerator__1_0[150];                   
                   //@ fold float_perm(_numerator__1_0);
                   {
                    float _numerator__1_1[150];
                    //@ fold float_perm(_numerator__1_1);
                    {
                     float _numerator__1_2[150];
                     //@ fold float_perm(_numerator__1_2);
                     {
                      float _numerator__1_3[150];
                      //@ fold float_perm(_numerator__1_3);
                      // produce numerator$1
                      /*@
                       loop_invariant 0 <= _numerator__1_s0_a && _numerator__1_s0_a <= 0 + 50;
                       loop_invariant float_perm(_numerator__1_0); 
                       loop_invariant float_perm(_numerator__1_1);
                       loop_invariant float_perm(_numerator__1_2);
                       loop_invariant float_perm(_numerator__1_3);

                    //    loop_invariant (\forall* int _numerator__1_s0_si_forall, int _numerator__1_s0_a_forall; 0 <= _numerator__1_s0_a_forall && _numerator__1_s0_a_forall < 50 && 0 <= _numerator__1_s0_si_forall && _numerator__1_s0_si_forall < 3; Perm(&_numerator__1_0[_numerator__1_s0_a_forall*3 + _numerator__1_s0_si_forall], 1\1));
                    //    loop_invariant (\forall* int _numerator__1_s0_si_forall, int _numerator__1_s0_a_forall; 0 <= _numerator__1_s0_a_forall && _numerator__1_s0_a_forall < 50 && 0 <= _numerator__1_s0_si_forall && _numerator__1_s0_si_forall < 3; Perm(&_numerator__1_1[_numerator__1_s0_a_forall*3 + _numerator__1_s0_si_forall], 1\1));
                    //    loop_invariant (\forall* int _numerator__1_s0_si_forall, int _numerator__1_s0_a_forall; 0 <= _numerator__1_s0_a_forall && _numerator__1_s0_a_forall < 50 && 0 <= _numerator__1_s0_si_forall && _numerator__1_s0_si_forall < 3; Perm(&_numerator__1_2[_numerator__1_s0_a_forall*3 + _numerator__1_s0_si_forall], 1\1));
                    //    loop_invariant (\forall* int _numerator__1_s0_si_forall, int _numerator__1_s0_a_forall; 0 <= _numerator__1_s0_a_forall && _numerator__1_s0_a_forall < 50 && 0 <= _numerator__1_s0_si_forall && _numerator__1_s0_si_forall < 3; Perm(&_numerator__1_3[_numerator__1_s0_a_forall*3 + _numerator__1_s0_si_forall], 1\1));
                      @*/
                      for (int _numerator__1_s0_a = 0; _numerator__1_s0_a < 0 + 50; _numerator__1_s0_a++)
                      {
                       int32_t _t12739 = (_numerator__1_s0_a * 3);
                       /*@
                        loop_invariant 0 <= _numerator__1_s0_si && _numerator__1_s0_si <= 0 + 3;
                        loop_invariant float_perm(_numerator__1_0); 
                        loop_invariant float_perm(_numerator__1_1);
                        loop_invariant float_perm(_numerator__1_2);
                        loop_invariant float_perm(_numerator__1_3);

                        // loop_invariant (\forall* int _numerator__1_s0_si_forall; 0 <= _numerator__1_s0_si_forall && _numerator__1_s0_si_forall < 3; Perm(&_numerator__1_0[_numerator__1_s0_a*3 + _numerator__1_s0_si_forall], 1\1));
                        // loop_invariant (\forall* int _numerator__1_s0_si_forall; 0 <= _numerator__1_s0_si_forall && _numerator__1_s0_si_forall < 3; Perm(&_numerator__1_1[_numerator__1_s0_a*3 + _numerator__1_s0_si_forall], 1\1));
                        // loop_invariant (\forall* int _numerator__1_s0_si_forall; 0 <= _numerator__1_s0_si_forall && _numerator__1_s0_si_forall < 3; Perm(&_numerator__1_2[_numerator__1_s0_a*3 + _numerator__1_s0_si_forall], 1\1));
                        // loop_invariant (\forall* int _numerator__1_s0_si_forall; 0 <= _numerator__1_s0_si_forall && _numerator__1_s0_si_forall < 3; Perm(&_numerator__1_3[_numerator__1_s0_a*3 + _numerator__1_s0_si_forall], 1\1));
                       @*/
                       for (int _numerator__1_s0_si = 0; _numerator__1_s0_si < 0 + 3; _numerator__1_s0_si++)
                       {
                        //@ unfold float_perm(_numerator__1_0);
                        _numerator__1_0[(_numerator__1_s0_si + _t12739)] = 0.000000;
                        //@ fold float_perm(_numerator__1_0);
                        //@ unfold float_perm(_numerator__1_1);
                        _numerator__1_1[(_numerator__1_s0_si + _t12739)] = 0.000000;
                        //@ fold float_perm(_numerator__1_1);
                        //@ unfold float_perm(_numerator__1_2);
                        _numerator__1_2[(_numerator__1_s0_si + _t12739)] = 0.000000;
                        //@ fold float_perm(_numerator__1_2);
                        //@ unfold float_perm(_numerator__1_3);
                        _numerator__1_3[(_numerator__1_s0_si + _t12739)] = 0.000000;
                        //@ fold float_perm(_numerator__1_3);
                       } // for _numerator__1_s0_si
                      } // for _numerator__1_s0_a
                      // consume cor_model_transp_1
                      // consume cor_model_2
                      /*@
                       loop_invariant 0 <= _numerator__1_s1_rv2__y && _numerator__1_s1_rv2__y <= 0 + 230930;
                       loop_invariant [1\2]int_perm_bound(_ant1, 0, 50);
                       
                       
                       loop_invariant [1\2]int_perm_bound(_ant2, 0, 50);
                       
                       
                       loop_invariant [1\2]float_perm(_model_);

                       
                       loop_invariant [1\2]double_perm(_sol_);                       
                       loop_invariant [1\2]int_perm_bound(_solution_map, 0, 3);
                       
                       
                       loop_invariant [1\2]float_perm(_v_res_in);

                       loop_invariant float_perm(_numerator__1_0); 
                       loop_invariant float_perm(_numerator__1_1);
                       loop_invariant float_perm(_numerator__1_2);
                       loop_invariant float_perm(_numerator__1_3);

                       loop_invariant [1\2]float_perm(_cor_model_2_0);
                       loop_invariant [1\2]float_perm(_cor_model_transp_1_0);

                    //    loop_invariant (\forall* int _numerator__1_s1_si_forall, int _numerator__1_s1_a_forall; 0 <= _numerator__1_s1_si_forall && _numerator__1_s1_si_forall < 3 && 0 <= _numerator__1_s1_a_forall && _numerator__1_s1_a_forall < 50; Perm(&_numerator__1_0[_numerator__1_s1_a_forall*3 + _numerator__1_s1_si_forall], 1\1));
                    //    loop_invariant (\forall* int _numerator__1_s1_si_forall, int _numerator__1_s1_a_forall; 0 <= _numerator__1_s1_si_forall && _numerator__1_s1_si_forall < 3 && 0 <= _numerator__1_s1_a_forall && _numerator__1_s1_a_forall < 50; Perm(&_numerator__1_1[_numerator__1_s1_a_forall*3 + _numerator__1_s1_si_forall], 1\1));
                    //    loop_invariant (\forall* int _numerator__1_s1_si_forall, int _numerator__1_s1_a_forall; 0 <= _numerator__1_s1_si_forall && _numerator__1_s1_si_forall < 3 && 0 <= _numerator__1_s1_a_forall && _numerator__1_s1_a_forall < 50; Perm(&_numerator__1_2[_numerator__1_s1_a_forall*3 + _numerator__1_s1_si_forall], 1\1));
                    //    loop_invariant (\forall* int _numerator__1_s1_si_forall, int _numerator__1_s1_a_forall; 0 <= _numerator__1_s1_si_forall && _numerator__1_s1_si_forall < 3 && 0 <= _numerator__1_s1_a_forall && _numerator__1_s1_a_forall < 50; Perm(&_numerator__1_3[_numerator__1_s1_a_forall*3 + _numerator__1_s1_si_forall], 1\1));
                      @*/
                      for (int _numerator__1_s1_rv2__y = 0; _numerator__1_s1_rv2__y < 0 + 230930; _numerator__1_s1_rv2__y++)
                      {
                       /*@
                        loop_invariant 0 <= _numerator__1_s1_rv2__x && _numerator__1_s1_rv2__x <= 0 + 2;
                        loop_invariant [1\2]int_perm_bound(_ant1, 0, 50);
                        
                        
                        loop_invariant [1\2]int_perm_bound(_ant2, 0, 50);
                        
                        
                        loop_invariant [1\2]float_perm(_model_);

                        
                        loop_invariant [1\2]double_perm(_sol_);                        
                        loop_invariant [1\2]int_perm_bound(_solution_map, 0, 3);
                        
                        
                        loop_invariant [1\2]float_perm(_v_res_in);

                        loop_invariant float_perm(_numerator__1_0); 
                        loop_invariant float_perm(_numerator__1_1);
                        loop_invariant float_perm(_numerator__1_2);
                        loop_invariant float_perm(_numerator__1_3);

                        loop_invariant [1\2]float_perm(_cor_model_2_0);
                        loop_invariant [1\2]float_perm(_cor_model_transp_1_0);


                        // loop_invariant (\forall* int _numerator__1_s1_si_forall, int _numerator__1_s1_a_forall; 0 <= _numerator__1_s1_si_forall && _numerator__1_s1_si_forall < 3 && 0 <= _numerator__1_s1_a_forall && _numerator__1_s1_a_forall < 50; Perm(&_numerator__1_0[_numerator__1_s1_a_forall*3 + _numerator__1_s1_si_forall], 1\1));
                        // loop_invariant (\forall* int _numerator__1_s1_si_forall, int _numerator__1_s1_a_forall; 0 <= _numerator__1_s1_si_forall && _numerator__1_s1_si_forall < 3 && 0 <= _numerator__1_s1_a_forall && _numerator__1_s1_a_forall < 50; Perm(&_numerator__1_1[_numerator__1_s1_a_forall*3 + _numerator__1_s1_si_forall], 1\1));
                        // loop_invariant (\forall* int _numerator__1_s1_si_forall, int _numerator__1_s1_a_forall; 0 <= _numerator__1_s1_si_forall && _numerator__1_s1_si_forall < 3 && 0 <= _numerator__1_s1_a_forall && _numerator__1_s1_a_forall < 50; Perm(&_numerator__1_2[_numerator__1_s1_a_forall*3 + _numerator__1_s1_si_forall], 1\1));
                        // loop_invariant (\forall* int _numerator__1_s1_si_forall, int _numerator__1_s1_a_forall; 0 <= _numerator__1_s1_si_forall && _numerator__1_s1_si_forall < 3 && 0 <= _numerator__1_s1_a_forall && _numerator__1_s1_a_forall < 50; Perm(&_numerator__1_3[_numerator__1_s1_a_forall*3 + _numerator__1_s1_si_forall], 1\1));
                       @*/
                       for (int _numerator__1_s1_rv2__x = 0; _numerator__1_s1_rv2__x < 0 + 2; _numerator__1_s1_rv2__x++)
                       {
                        {
                         float _numerator_inter__1_0[2];
                         {
                          float _numerator_inter__1_1[2];
                          {
                           float _numerator_inter__1_2[2];
                           {
                            float _numerator_inter__1_3[2];
                            
                           } // alloc _numerator_inter__1_3
                          } // alloc _numerator_inter__1_2
                         } // alloc _numerator_inter__1_1
                        } // alloc _numerator_inter__1_0
                       } // for _numerator__1_s1_rv2__x
                      } // for _numerator__1_s1_rv2__y
                    //   free(_cor_model_2_0);
                    //   free(_cor_model_2_1);
                    //   free(_cor_model_2_2);
                    //   free(_cor_model_2_3);
                    //   free(_cor_model_2_4);
                    //   free(_cor_model_2_5);
                    //   free(_cor_model_2_6);
                    //   free(_cor_model_2_7);
                    //   free(_cor_model_transp_1_0);
                    //   free(_cor_model_transp_1_1);
                    //   free(_cor_model_transp_1_2);
                    //   free(_cor_model_transp_1_3);
                    //   free(_cor_model_transp_1_4);
                    //   free(_cor_model_transp_1_5);
                    //   free(_cor_model_transp_1_6);
                    //   free(_cor_model_transp_1_7);
                      // produce next_solutions_complex
                      // consume numerator$1
                      // consume denominator$1
                      /*@
                       loop_invariant 0 <= _next_solutions_complex_s0_a && _next_solutions_complex_s0_a <= 0 + 50;
                       
                       loop_invariant [1\2]float_perm(_denominator__1);
                       loop_invariant [1\2]float_perm(_numerator__1_0);
                       loop_invariant [1\2]float_perm(_numerator__1_1);
                       loop_invariant [1\2]float_perm(_numerator__1_2);
                       loop_invariant [1\2]float_perm(_numerator__1_3);

                       loop_invariant double_perm(_next_solutions_complex);
                      @*/
                      for (int _next_solutions_complex_s0_a = 0; _next_solutions_complex_s0_a < 0 + 50; _next_solutions_complex_s0_a++)
                      {
                       int32_t _t12742 = (_next_solutions_complex_s0_a * 32);
                       int32_t _t12741 = (_next_solutions_complex_s0_a * 3);
                       /*@
                        loop_invariant 0 <= _next_solutions_complex_s0_si && _next_solutions_complex_s0_si <= 0 + 3;
                        loop_invariant [1\2]float_perm(_denominator__1);
                        loop_invariant [1\2]float_perm(_numerator__1_0);
                        loop_invariant [1\2]float_perm(_numerator__1_1);
                        loop_invariant [1\2]float_perm(_numerator__1_2);
                        loop_invariant [1\2]float_perm(_numerator__1_3);

                        loop_invariant double_perm(_next_solutions_complex);
                       @*/
                       for (int _next_solutions_complex_s0_si = 0; _next_solutions_complex_s0_si < 0 + 3; _next_solutions_complex_s0_si++)
                       {
                        int32_t _t12746 = (_next_solutions_complex_s0_si + _t12741);
                        int32_t _t12745 = ((_next_solutions_complex_s0_si * 4) + _t12742);
                        /*@
                         loop_invariant 0 <= _next_solutions_complex_s0_pol && _next_solutions_complex_s0_pol <= 0 + 2;
                         loop_invariant [1\2]float_perm(_denominator__1);
                         loop_invariant [1\2]float_perm(_numerator__1_0);
                         loop_invariant [1\2]float_perm(_numerator__1_1);
                         loop_invariant [1\2]float_perm(_numerator__1_2);
                         loop_invariant [1\2]float_perm(_numerator__1_3);
 
                         loop_invariant double_perm(_next_solutions_complex);
                        @*/
                        for (int _next_solutions_complex_s0_pol = 0; _next_solutions_complex_s0_pol < 0 + 2; _next_solutions_complex_s0_pol++)
                        {
                         bool _t12748 = (_next_solutions_complex_s0_pol == 0);
                         int32_t _t12749 = ((_next_solutions_complex_s0_pol * 2) + _t12745);
                         /*@
                          loop_invariant 0 <= _next_solutions_complex_s0_c && _next_solutions_complex_s0_c <= 0 + 2;
                          loop_invariant [1\2]float_perm(_denominator__1);
                          loop_invariant [1\2]float_perm(_numerator__1_0);
                          loop_invariant [1\2]float_perm(_numerator__1_1);
                          loop_invariant [1\2]float_perm(_numerator__1_2);
                          loop_invariant [1\2]float_perm(_numerator__1_3);
  
                          loop_invariant double_perm(_next_solutions_complex);
                         @*/
                         for (int _next_solutions_complex_s0_c = 0; _next_solutions_complex_s0_c < 0 + 2; _next_solutions_complex_s0_c++)
                         {
                          {
                           double _next_solutions_inter_0[2];
                           {
                            double _next_solutions_inter_1[2];
                            // produce next_solutions_inter
                            // float _593 = _denominator__1[(_t12746 * 2)];
                            // float _t12682 = _593;
                            // float _594 = _numerator__1_0[_t12746];
                            // double _595 = (double)(_594);
                            // double _596 = (double)(_t12682);
                            // _next_solutions_inter_0[0] = ((_t12682 == 0.000000) ? nan_f32() : (_595 / _596));
                            // float _597 = _denominator__1[(_t12746 * 2)];
                            // float _t12684 = _597;
                            // float _598 = _numerator__1_1[_t12746];
                            // double _599 = (double)(_598);
                            // double _600 = (double)(_t12684);
                            // _next_solutions_inter_1[0] = ((_t12684 == 0.000000) ? nan_f32() : (_599 / _600));
                            // float _601 = _denominator__1[((_t12746 * 2) + 1)];
                            // float _t12686 = _601;
                            // float _602 = _numerator__1_2[_t12746];
                            // double _603 = (double)(_602);
                            // double _604 = (double)(_t12686);
                            // _next_solutions_inter_0[1] = ((_t12686 == 0.000000) ? nan_f32() : (_603 / _604));
                            // float _605 = _denominator__1[((_t12746 * 2) + 1)];
                            // float _t12688 = _605;
                            // float _606 = _numerator__1_3[_t12746];
                            // double _607 = (double)(_606);
                            // double _608 = (double)(_t12688);
                            // _next_solutions_inter_1[1] = ((_t12688 == 0.000000) ? nan_f32() : (_607 / _608));
                            // // consume next_solutions_inter
                            // double _609 = _next_solutions_inter_0[0];
                            // double _610 = _next_solutions_inter_0[1];
                            // double _611 = _next_solutions_inter_1[0];
                            // double _612 = _next_solutions_inter_1[1];
                            // _next_solutions_complex[(_next_solutions_complex_s0_c + _t12749)] = ((_next_solutions_complex_s0_c == 0) ? (_t12748 ? _609 : _610) : ((_next_solutions_complex_s0_c == 1) ? (_t12748 ? _611 : _612) : (_t12748 ? _611 : _612)));
                           } // alloc _next_solutions_inter_1
                          } // alloc _next_solutions_inter_0
                         } // for _next_solutions_complex_s0_c
                        } // for _next_solutions_complex_s0_pol
                       } // for _next_solutions_complex_s0_si
                      } // for _next_solutions_complex_s0_a
                     } // alloc _numerator__1_3
                    } // alloc _numerator__1_2
                   } // alloc _numerator__1_1
                  } // alloc _numerator__1_0
                 } // alloc _denominator__1
                } // alloc _cor_model_transp_1_7
               } // alloc _cor_model_transp_1_6
              } // alloc _cor_model_transp_1_5
             } // alloc _cor_model_transp_1_4
            } // alloc _cor_model_transp_1_3
           } // alloc _cor_model_transp_1_2
          } // alloc _cor_model_transp_1_1
         } // alloc _cor_model_transp_1_0
        } // alloc _cor_model_2_7
       } // alloc _cor_model_2_6
      } // alloc _cor_model_2_5
     } // alloc _cor_model_2_4
    } // alloc _cor_model_2_3
   } // alloc _cor_model_2_2
  } // alloc _cor_model_2_1
 } // alloc _cor_model_2_0
 return 0;
}

#ifdef __cplusplus
}  // extern "C"
#endif

